# Generated by Django 3.2.9 on 2021-11-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=70)),
                ('house_number', models.CharField(blank=True, max_length=10)),
                ('flat_number', models.CharField(blank=True, max_length=10)),
                ('code', models.CharField(blank=True, max_length=6)),
                ('city', models.CharField(blank=True, max_length=70)),
                ('province', models.CharField(blank=True, max_length=70)),
                ('roof_covering', models.CharField(choices=[('Blachodachówka Novotegra', 'Blachodachówka Novotegra'), ('Dachówka Ceramiczna Novotegra', 'Dachówka Ceramiczna Novotegra'), ('Blachotrapez Novotegra', 'Blachotrapez Novotegra'), ('Aero Południe Novotegra', 'Aero Południe Novotegra'), ('Aero Wschód-Zachód Novotegra', 'Aero Wschód-Zachód Novotegra'), ('Grunt CORAB', 'Grunt CORAB')], max_length=70)),
                ('roof_type', models.CharField(blank=True, max_length=70)),
                ('roof_slope', models.PositiveSmallIntegerField(default=0)),
                ('roof_orientation', models.PositiveSmallIntegerField(default=0)),
                ('roof_direction', models.CharField(blank=True, max_length=70)),
                ('windows_number', models.IntegerField(default=0)),
                ('chimney_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=70)),
                ('last_name', models.CharField(blank=True, max_length=70)),
                ('street', models.CharField(blank=True, max_length=70)),
                ('house_number', models.CharField(blank=True, max_length=10)),
                ('flat_number', models.CharField(blank=True, max_length=10)),
                ('code', models.CharField(blank=True, max_length=6)),
                ('city', models.CharField(blank=True, max_length=70)),
                ('province', models.CharField(blank=True, max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=8)),
                ('PESEL', models.PositiveSmallIntegerField(default=0, max_length=11)),
                ('phone_number', models.CharField(blank=True, max_length=70)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_contact_date', models.DateField(auto_now_add=True)),
                ('last_contact_date', models.DateField(auto_now=True)),
                ('company', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveSmallIntegerField()),
                ('modules', models.CharField(blank=True, max_length=70)),
                ('modules_number', models.PositiveSmallIntegerField(default=1)),
                ('inverter_producer', models.CharField(blank=True, max_length=70)),
                ('inverter_model', models.CharField(blank=True, max_length=70)),
                ('inverter_number', models.PositiveSmallIntegerField(default=1)),
                ('optimizer', models.CharField(blank=True, max_length=70)),
                ('optimizer_number', models.PositiveSmallIntegerField(default=0)),
                ('add_warranty', models.BooleanField(default=False)),
                ('add_component_1', models.CharField(max_length=70)),
                ('add_component_2', models.CharField(max_length=70)),
                ('add_component_3', models.CharField(max_length=70)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.building')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='my_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=70)),
                ('netto_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brutto_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_moj_prad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_refund', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.building')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferts', to='my_app.client')),
                ('installation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.installation')),
            ],
        ),
    ]
