# Generated by Django 3.2.9 on 2021-11-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='client_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='my_app.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='roof_slope',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (90, '90')], default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='roof_type',
            field=models.CharField(choices=[('dach skośny', 'dach skośny'), ('dach płaski', 'dach płaski'), ('grunt', 'grunt')], max_length=70),
        ),
        migrations.AlterField(
            model_name='client',
            name='PESEL',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('woj. dolnośląskie', 'woj. dolnośląskie'), ('woj. kujawsko-pomorskie', 'woj. kujawsko-pomorskie'), ('woj. lubelskie', 'woj. lubelskie'), ('woj. lubuskie', 'woj. lubuskie'), ('woj. łódzkie', 'woj. łódzkie'), ('woj. małopolskie', 'woj. małopolskie'), ('woj. mazowieckie', 'woj. mazowieckie'), ('woj. opolskie', 'woj. opolskie'), ('woj. podkarpackie', 'woj. podkarpackie'), ('woj. podlaskie', 'woj. podlaskie'), ('woj. pomorskie', 'woj. pomorskie'), ('woj. śląskie', 'woj. śląskie'), ('woj. świętokrzyskie', 'woj. świętokrzyskie'), ('woj. warmińsko-mazurskie', 'woj. warmińsko-mazurskie'), ('woj. wielkopolskie', 'woj. wielkopolskie'), ('woj. zachodniopomorskie', 'woj. zachodniopomorskie')], max_length=24),
        ),
    ]
